inherit_from: .rubocop_todo.yml

inherit_gem:
  theforeman-rubocop:
    - lenient.yml

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
